POST https://backend-nodejs-starter.onrender.com/videos
Content-type: application/json
Accept-Language: pt

{
    "title": "video 01",
    "description": "video",
    "duration": 180
}

###

GET https://backend-nodejs-starter.onrender.com/videos

###

PUT https://backend-nodejs-starter.onrender.com/videos/8d8aadea-95ef-44c4-a73c-d42b64c00540
Content-type: application/json
Accept-Language: pt
{
    "title": "video 02",
    "description": "video",
    "duration": 180
}

###

DELETE https://backend-nodejs-starter.onrender.com/videos/8d8aadea-95ef-44c4-a73c-d42b64c00540


